"""Minimal bootstrap data used by seeds and tests.

The goal is to keep the foundation deterministic and small while still
making the read-only reference endpoints useful immediately after setup.
"""

from __future__ import annotations

SIGNS = [
    {
        "code": "ARIES",
        "name_pt": "Áries",
        "name_en": "Aries",
        "symbol": "♈",
        "order_num": 1,
        "element": "fire",
        "modality": "cardinal",
        "polarity": "yang",
        "start_degree": 0.0,
        "end_degree": 30.0,
    },
    {
        "code": "TAURUS",
        "name_pt": "Touro",
        "name_en": "Taurus",
        "symbol": "♉",
        "order_num": 2,
        "element": "earth",
        "modality": "fixed",
        "polarity": "yin",
        "start_degree": 30.0,
        "end_degree": 60.0,
    },
    {
        "code": "GEMINI",
        "name_pt": "Gêmeos",
        "name_en": "Gemini",
        "symbol": "♊",
        "order_num": 3,
        "element": "air",
        "modality": "mutable",
        "polarity": "yang",
        "start_degree": 60.0,
        "end_degree": 90.0,
    },
    {
        "code": "CANCER",
        "name_pt": "Câncer",
        "name_en": "Cancer",
        "symbol": "♋",
        "order_num": 4,
        "element": "water",
        "modality": "cardinal",
        "polarity": "yin",
        "start_degree": 90.0,
        "end_degree": 120.0,
    },
    {
        "code": "LEO",
        "name_pt": "Leão",
        "name_en": "Leo",
        "symbol": "♌",
        "order_num": 5,
        "element": "fire",
        "modality": "fixed",
        "polarity": "yang",
        "start_degree": 120.0,
        "end_degree": 150.0,
    },
    {
        "code": "VIRGO",
        "name_pt": "Virgem",
        "name_en": "Virgo",
        "symbol": "♍",
        "order_num": 6,
        "element": "earth",
        "modality": "mutable",
        "polarity": "yin",
        "start_degree": 150.0,
        "end_degree": 180.0,
    },
    {
        "code": "LIBRA",
        "name_pt": "Libra",
        "name_en": "Libra",
        "symbol": "♎",
        "order_num": 7,
        "element": "air",
        "modality": "cardinal",
        "polarity": "yang",
        "start_degree": 180.0,
        "end_degree": 210.0,
    },
    {
        "code": "SCORPIO",
        "name_pt": "Escorpião",
        "name_en": "Scorpio",
        "symbol": "♏",
        "order_num": 8,
        "element": "water",
        "modality": "fixed",
        "polarity": "yin",
        "start_degree": 210.0,
        "end_degree": 240.0,
    },
    {
        "code": "SAGITTARIUS",
        "name_pt": "Sagitário",
        "name_en": "Sagittarius",
        "symbol": "♐",
        "order_num": 9,
        "element": "fire",
        "modality": "mutable",
        "polarity": "yang",
        "start_degree": 240.0,
        "end_degree": 270.0,
    },
    {
        "code": "CAPRICORN",
        "name_pt": "Capricórnio",
        "name_en": "Capricorn",
        "symbol": "♑",
        "order_num": 10,
        "element": "earth",
        "modality": "cardinal",
        "polarity": "yin",
        "start_degree": 270.0,
        "end_degree": 300.0,
    },
    {
        "code": "AQUARIUS",
        "name_pt": "Aquário",
        "name_en": "Aquarius",
        "symbol": "♒",
        "order_num": 11,
        "element": "air",
        "modality": "fixed",
        "polarity": "yang",
        "start_degree": 300.0,
        "end_degree": 330.0,
    },
    {
        "code": "PISCES",
        "name_pt": "Peixes",
        "name_en": "Pisces",
        "symbol": "♓",
        "order_num": 12,
        "element": "water",
        "modality": "mutable",
        "polarity": "yin",
        "start_degree": 330.0,
        "end_degree": 360.0,
    },
]

SIGN_OPPOSITES = {
    "ARIES": "LIBRA",
    "TAURUS": "SCORPIO",
    "GEMINI": "SAGITTARIUS",
    "CANCER": "CAPRICORN",
    "LEO": "AQUARIUS",
    "VIRGO": "PISCES",
    "LIBRA": "ARIES",
    "SCORPIO": "TAURUS",
    "SAGITTARIUS": "GEMINI",
    "CAPRICORN": "CANCER",
    "AQUARIUS": "LEO",
    "PISCES": "VIRGO",
}

BODIES = [
    {
        "code": "SUN",
        "name_pt": "Sol",
        "name_en": "Sun",
        "symbol": "☉",
        "category": "personal",
        "is_personal": True,
        "is_luminary": True,
        "is_retrograde_capable": False,
        "orbital_period_days": 365.256,
        "average_daily_motion": 0.9856,
        "domicile_signs": ["LEO"],
        "exaltation_sign": "ARIES",
    },
    {
        "code": "MOON",
        "name_pt": "Lua",
        "name_en": "Moon",
        "symbol": "☽",
        "category": "personal",
        "is_personal": True,
        "is_luminary": True,
        "is_retrograde_capable": False,
        "orbital_period_days": 27.32166,
        "average_daily_motion": 13.1764,
        "domicile_signs": ["CANCER"],
        "exaltation_sign": "TAURUS",
    },
    {
        "code": "MERCURY",
        "name_pt": "Mercúrio",
        "name_en": "Mercury",
        "symbol": "☿",
        "category": "personal",
        "is_personal": True,
        "is_luminary": False,
        "is_retrograde_capable": True,
        "orbital_period_days": 87.969,
        "average_daily_motion": 4.0923,
        "domicile_signs": ["GEMINI", "VIRGO"],
        "exaltation_sign": "VIRGO",
    },
    {
        "code": "VENUS",
        "name_pt": "Vênus",
        "name_en": "Venus",
        "symbol": "♀",
        "category": "personal",
        "is_personal": True,
        "is_luminary": False,
        "is_retrograde_capable": True,
        "orbital_period_days": 224.701,
        "average_daily_motion": 1.6021,
        "domicile_signs": ["TAURUS", "LIBRA"],
        "exaltation_sign": "PISCES",
    },
    {
        "code": "MARS",
        "name_pt": "Marte",
        "name_en": "Mars",
        "symbol": "♂",
        "category": "personal",
        "is_personal": True,
        "is_luminary": False,
        "is_retrograde_capable": True,
        "orbital_period_days": 686.98,
        "average_daily_motion": 0.524,
        "domicile_signs": ["ARIES", "SCORPIO"],
        "exaltation_sign": "CAPRICORN",
    },
    {
        "code": "JUPITER",
        "name_pt": "Júpiter",
        "name_en": "Jupiter",
        "symbol": "♃",
        "category": "social",
        "is_personal": False,
        "is_luminary": False,
        "is_retrograde_capable": True,
        "orbital_period_days": 4332.59,
        "average_daily_motion": 0.0831,
        "domicile_signs": ["SAGITTARIUS", "PISCES"],
        "exaltation_sign": "CANCER",
    },
    {
        "code": "SATURN",
        "name_pt": "Saturno",
        "name_en": "Saturn",
        "symbol": "♄",
        "category": "social",
        "is_personal": False,
        "is_luminary": False,
        "is_retrograde_capable": True,
        "orbital_period_days": 10759.22,
        "average_daily_motion": 0.0335,
        "domicile_signs": ["CAPRICORN", "AQUARIUS"],
        "exaltation_sign": "LIBRA",
    },
    {
        "code": "URANUS",
        "name_pt": "Urano",
        "name_en": "Uranus",
        "symbol": "♅",
        "category": "transpersonal",
        "is_personal": False,
        "is_luminary": False,
        "is_retrograde_capable": True,
        "orbital_period_days": 30688.5,
        "average_daily_motion": 0.0117,
        "domicile_signs": ["AQUARIUS"],
        "exaltation_sign": "SCORPIO",
    },
    {
        "code": "NEPTUNE",
        "name_pt": "Netuno",
        "name_en": "Neptune",
        "symbol": "♆",
        "category": "transpersonal",
        "is_personal": False,
        "is_luminary": False,
        "is_retrograde_capable": True,
        "orbital_period_days": 60182.0,
        "average_daily_motion": 0.006,
        "domicile_signs": ["PISCES"],
        "exaltation_sign": "LEO",
    },
    {
        "code": "PLUTO",
        "name_pt": "Plutão",
        "name_en": "Pluto",
        "symbol": "♇",
        "category": "transpersonal",
        "is_personal": False,
        "is_luminary": False,
        "is_retrograde_capable": True,
        "orbital_period_days": 90560.0,
        "average_daily_motion": 0.004,
        "domicile_signs": ["SCORPIO"],
        "exaltation_sign": "ARIES",
    },
    {
        "code": "CHIRON",
        "name_pt": "Quíron",
        "name_en": "Chiron",
        "symbol": "⚷",
        "category": "asteroid",
        "is_personal": False,
        "is_luminary": False,
        "is_retrograde_capable": True,
        "orbital_period_days": 18524.0,
        "average_daily_motion": 0.02,
    },
    {
        "code": "NORTH_NODE",
        "name_pt": "Nodo Norte",
        "name_en": "North Node",
        "symbol": "☊",
        "category": "node",
        "is_personal": False,
        "is_luminary": False,
        "is_retrograde_capable": False,
        "average_daily_motion": -0.053,
    },
    {
        "code": "SOUTH_NODE",
        "name_pt": "Nodo Sul",
        "name_en": "South Node",
        "symbol": "☋",
        "category": "node",
        "is_personal": False,
        "is_luminary": False,
        "is_retrograde_capable": False,
        "average_daily_motion": -0.053,
    },
]

HOUSES = [
    {"number": 1, "name_pt": "Casa 1", "name_en": "House 1", "position_type": "angular", "natural_sign_code": "ARIES", "natural_body_code": "MARS", "opposite_house_number": 7},
    {"number": 2, "name_pt": "Casa 2", "name_en": "House 2", "position_type": "succedent", "natural_sign_code": "TAURUS", "natural_body_code": "VENUS", "opposite_house_number": 8},
    {"number": 3, "name_pt": "Casa 3", "name_en": "House 3", "position_type": "cadent", "natural_sign_code": "GEMINI", "natural_body_code": "MERCURY", "opposite_house_number": 9},
    {"number": 4, "name_pt": "Casa 4", "name_en": "House 4", "position_type": "angular", "natural_sign_code": "CANCER", "natural_body_code": "MOON", "opposite_house_number": 10},
    {"number": 5, "name_pt": "Casa 5", "name_en": "House 5", "position_type": "succedent", "natural_sign_code": "LEO", "natural_body_code": "SUN", "opposite_house_number": 11},
    {"number": 6, "name_pt": "Casa 6", "name_en": "House 6", "position_type": "cadent", "natural_sign_code": "VIRGO", "natural_body_code": "MERCURY", "opposite_house_number": 12},
    {"number": 7, "name_pt": "Casa 7", "name_en": "House 7", "position_type": "angular", "natural_sign_code": "LIBRA", "natural_body_code": "VENUS", "opposite_house_number": 1},
    {"number": 8, "name_pt": "Casa 8", "name_en": "House 8", "position_type": "succedent", "natural_sign_code": "SCORPIO", "natural_body_code": "MARS", "opposite_house_number": 2},
    {"number": 9, "name_pt": "Casa 9", "name_en": "House 9", "position_type": "cadent", "natural_sign_code": "SAGITTARIUS", "natural_body_code": "JUPITER", "opposite_house_number": 3},
    {"number": 10, "name_pt": "Casa 10", "name_en": "House 10", "position_type": "angular", "natural_sign_code": "CAPRICORN", "natural_body_code": "SATURN", "opposite_house_number": 4},
    {"number": 11, "name_pt": "Casa 11", "name_en": "House 11", "position_type": "succedent", "natural_sign_code": "AQUARIUS", "natural_body_code": "SATURN", "opposite_house_number": 5},
    {"number": 12, "name_pt": "Casa 12", "name_en": "House 12", "position_type": "cadent", "natural_sign_code": "PISCES", "natural_body_code": "JUPITER", "opposite_house_number": 6},
]

ASPECTS = [
    {"code": "CONJUNCTION", "name_pt": "Conjunção", "name_en": "Conjunction", "symbol": "☌", "angle_degrees": 0.0, "max_orb_default": 8.0, "quality": "major", "nature": "neutral"},
    {"code": "SEXTILE", "name_pt": "Sextil", "name_en": "Sextile", "symbol": "⚹", "angle_degrees": 60.0, "max_orb_default": 4.0, "quality": "major", "nature": "harmonic"},
    {"code": "SQUARE", "name_pt": "Quadratura", "name_en": "Square", "symbol": "□", "angle_degrees": 90.0, "max_orb_default": 6.0, "quality": "major", "nature": "tense"},
    {"code": "TRINE", "name_pt": "Trígono", "name_en": "Trine", "symbol": "△", "angle_degrees": 120.0, "max_orb_default": 6.0, "quality": "major", "nature": "harmonic"},
    {"code": "OPPOSITION", "name_pt": "Oposição", "name_en": "Opposition", "symbol": "☍", "angle_degrees": 180.0, "max_orb_default": 8.0, "quality": "major", "nature": "tense"},
]

ANGLES = [
    {"code": "ASC", "name_pt": "Ascendente", "name_en": "Ascendant", "abbreviation": "ASC", "opposite_angle_code": "DSC", "associated_house_number": 1},
    {"code": "MC", "name_pt": "Meio do Céu", "name_en": "Midheaven", "abbreviation": "MC", "opposite_angle_code": "IC", "associated_house_number": 10},
    {"code": "DSC", "name_pt": "Descendente", "name_en": "Descendant", "abbreviation": "DSC", "opposite_angle_code": "ASC", "associated_house_number": 7},
    {"code": "IC", "name_pt": "Fundo do Céu", "name_en": "Imum Coeli", "abbreviation": "IC", "opposite_angle_code": "MC", "associated_house_number": 4},
]

SCHOOLS = [
    {
        "code": "luz_e_sombra",
        "name_pt": "Luz e Sombra",
        "name_en": "Light and Shadow",
        "description": "Escola editorial inicial para a fundação do sistema.",
        "primary_authors": ["Claudia Lisboa"],
        "origin_country": "BR",
        "origin_decade": 1990,
        "is_active": True,
    },
    {
        "code": "hellenistic",
        "name_pt": "Astrologia Helenística",
        "name_en": "Hellenistic Astrology",
        "description": "Sistema editorial técnico para interpretações modulares em astrologia helenística.",
        "primary_authors": ["Valens", "Dorotheus", "Rhetorius"],
        "origin_country": "EG",
        "origin_decade": 100,
        "is_active": True,
    }
]
